name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build and test
    - run: npm install
    - run: npm run build
    - run: npm test
    - name: Deploy
      uses: sheldon37/GitLab2
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build